# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mynetflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
